<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>

    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>

    <AssemblyName>FOff</AssemblyName>
    <RootNamespace>FOff</RootNamespace>
    <Version>0.3.0</Version>

    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>


    <ValheimDir Condition="'$(ValheimDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimDir>
    <ValheimManaged Condition="'$(ValheimManaged)' == ''">$(ValheimDir)\valheim_Data\Managed</ValheimManaged>
    <PublicizedAssemblies Condition="'$(PublicizedAssemblies)' == ''">$(ValheimManaged)\publicized_assemblies</PublicizedAssemblies>


    <BepInExLibDir Condition="'$(BepInExLibDir)' == ''">C:\ValheimShit\libs</BepInExLibDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExLibDir)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>$(BepInExLibDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="assembly_valheim">
      <HintPath>$(PublicizedAssemblies)\assembly_valheim_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>$(ValheimManaged)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ValheimManaged)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(ValheimManaged)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>